/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'pablo' at '05/07/16 23:07' with Gradle 2.3
 *
 * @author pablo, @date 05/07/16 23:07
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
